[ch01~ch02] 학습 내용을 적용할 레거시 코드 업데이트
joco-naco-study/practice-with-legacy pull request #2
Opened 2024-12-31 07:00 UTC by jsoonworld

2025-01-02 08:31 UTC, minSsan requested changes
지난번에 프로젝트할 때 개인적으로 공부했던 부분이랑 비슷한 부분이 보여서, 이 부분 먼저 코멘트 남깁니다 ~

2025-01-02 08:31 UTC, minSsan commented on ch01~ch02/service/AppleService.java
## 인터페이스만을 위한 인터페이스?
> 책 52쪽 참고

`AppleService`와 `KakaoService`의 인터페이스를 따로 분리할 필요가 있을까?

### 문제점
두 클래스 모두 하는 역할은 공통적 _(= 액세스 토큰으로 유저 데이터를 추출하는 것)_ 이나, **인터페이스가 분리**되어 있고 **각 인터페이스의 구현체 또한 각각 하나씩만 존재하는 것**을 확인할 수 있다.

두 클래스의 역할을 살펴보면 이들은 하나로 통일할 수 있을 것으로 보이며, 교재 49페이지에 설명되어있는 예제 _(팩토리 함수를 통한 구현체 매핑 등)_ 를 활용하여 더 큰 범위의 추상화로 개선할 수 있을 것이다. (:: 애플 로그인 / 카카오 로그인 추상화 👉🏻 **소셜 로그인 추상화**)

### 해결 방안
> 즉, 소셜 로그인 역할을 하는 클래스를 하나로 추상화 하고, 이 소셜 로그인 클래스의 퍼블릭 함수는 `getData` (= 액세스 토큰을 통해 데이터를 추출)가 될 것이다.

따라서 `AppleService`와 `KakaoService`를 `OauthService`로 통합하고, 아래와 같은 구조로 변경하는 방법을 제시

- `OauthService` 추상 객체
```java
public interface OauthService {
    String getData(String authAccessToken);
}
```
- `AppleService` 구현체
```java
public class AppleService implements OauthService {
    @Override
    String getData(String authAccessToken) {
        // ...
    }

    // ... 필요한 private 메서드 정의 ...
}
```
- `KakaoService` 구현체
```java
public class KakaoService implements OauthService {
    @Override
    String getData(String authAccessToken) {
        // ...
    }

    // ... 필요한 private 메서드 정의 ...
}
```

그리고 여기서 사용자가 요청한 소셜 로그인에 따라 서로 다른 구현체를 매핑해야 한다.
이 방법에 대해서는 책에서 두 가지 방법을 제시하고 있는데, 첫 번째는 **팩토리 패턴**를 사용하는 것이고 두 번째는 **의존성 주입 프레임워크**를 사용하는 것이다.

## 구현체 매핑
### 1. 팩토리 패턴 사용
```java
public class OauthServiceFactory {
    public OauthService get(AuthType authType) {
        switch (authType) {
            case APPLE:
                return new AppleService();
            case KAKAO:
                return new KakaoService();
            default:
                return null;
        }
    }
}
```

이렇게 되면 다이어그램은 대략 아래와 같아질 것이다.
<img width="569" alt="image" src="https://github.com/user-attachments/assets/43d499e0-cb0f-45d4-95e1-7d3c521f40ba" />

컨트롤러에서 API에 명시된 소셜 로그인 종류(`AuthType`)를 팩토리 클래스에 전달하고, 알맞은 `OauthService` 구현체를 호출하는 식으로 사용될 것이다.

### 2. 의존성 주입 (with `Spring`)
하지만 위 방식은 스프링 빈에 등록되어 있는 구현체를 리턴하는 것이 아니라, **해당 메소드를 호출할 때마다 새로운 구현체를 생성해서 리턴**하고 있다.
> 만약 스프링 빈에 등록되어 있는 구현체를 리턴하고자 한다면 어떻게 해야할까?

일단 `KakaoService` 및 `AppleService` 클래스 모두 스프링 빈에 등록되어 있다는 가정 하에(`@Service` 어노테이션 사용 등을 통해) 살펴본다.

스프링에서는 아래와 같이 타입을 선언하면, 빈에 등록된 클래스 중에서 해당 타입을 갖는 모든 구현체를 자동으로 매핑해준다.
```java
public class BeanExample {
    List<OauthService> oauthServices; // {KakaoService, AppleService}
}
```
이를 활용한다면, 일단 리스트를 순회하며 사용자가 원하는 `OauthService` 구현체를 찾아서 리턴할 수 있을 것이다.
하지만, 위의 팩토리 패턴처럼 구현체를 생성해서 리턴하는 것이 아닌, **`oauthServices` 리스트에 있는 구현체를 리턴해야** 한다.
> 즉, 리스트에 등록 되어있는 구현체가 "카카오 소셜 로그인"인지, "애플 소셜 로그인"인지 판별할 수 있어야 한다. 그리고 이를 토대로 요청된 `AuthType`과 매칭되는 것을 찾아서 리턴해야 한다. 

즉, 각 구현체는 자신이 "카카오 소셜 로그인" 역할인지 "애플 소셜 로그인" 역할인지 외부에 알려줘야 하므로, 인터페이스에 다음과 같은 메소드를 추가할 수 있다.

```java
public interface OauthService {
    String getData(String authAccessToken);
    AuthType getAuthType();
}
```

그리고 각 구현체는 다음과 같이 수정할 수 있다.

- `AppleService` 구현체
```java
public class AppleService implements OauthService {
    @Override
    String getData(String authAccessToken) {
        // ...
    }

    @Override
    AuthType getAuthType() {
        return AuthType.APPLE;
    }

    // ... 필요한 private 메서드 정의 ...
}
```
- `KakaoService` 구현체
```java
public class KakaoService implements OauthService {
    @Override
    String getData(String authAccessToken) {
        // ...
    }

    @Override
    AuthType getAuthType() {
        return AuthType.KAKAO;
    }

    // ... 필요한 private 메서드 정의 ...
}
```

그리고 이렇게 수정한 내용을 토대로 팩토리 클래스는 아래와 같이 변경될 수 있다.
```java
public class OauthServiceFactory {
    private final List<OauthService> services;

    public OauthService get(AuthType authType) {
        return services.stream()
                .filter(s -> s.getAuthType() == authType)
                .findAny()
                .orElseThrow(() -> ...);
    }
}
```
이 경우 팩토리 클래스를 별도로 정의하지 않고, 위의 메소드를 컨트롤러 내부에 선언하여 바로 사용하여도 크게 상관이 없을 것 같다는 생각이 든다. . . 책에서 제시한 해결책이 "팩토리 패턴 사용 or 의존성 주입" 뉘앙스 같아서 ..(아마도?)

## 기대 효과
기존 방식의 경우 `새로운 소셜 로그인이 추가`될 때마다 인터페이스 + 구현체 선언이 모두 필요했다면, 코드 개선 이후에는 구현체만 선언하면 끝난다.
특히, **스프링 빈 의존성 주입**을 활용한다면 팩토리 메소드 수정도 불필요하기 때문에 확장에 용이하다는 장점이 더 부각될 것 같다.

2025-01-04 15:51 UTC, minSsan commented on ch01~ch02/service/AuthServiceImpl.java
> +    }
## 테스트가 어려운 코드
해당 메소드를 테스트하는 과정을 떠올려보면 테스트가 쉽지 않아 보인다.
> 테스트 과정에서 `authAccessToken`을 직접 생성해서 해야 함   
> 또한, 해당 메소드를 사용하는 과정에서 의존하는 객체가 많음 (= 모킹 객체가 많아짐)

### 원인 분석
이러한 문제가 발생하는 이유에 대해 생각하기 위해, 우선 함수가 맡고 있는 역할이 무엇인지 살펴보았다.

여기서 `signIn` 함수의 역할을 더 정확하게 설명하면
```
액세스 토큰에서 authId를 추출한 후, 알맞은 유저 정보를 찾아서 응답 객체를 리턴하는 것
```
이 될 것이다.

### 클래스 분리
컨트롤러가 어떤식으로 동작 하는지는 잘 모르겠지만, 여기서 `액세스 토큰에서 authId를 추출하는 부분`은 별도의 클래스(ex. `TokenResolver`)로 분리하는 방법은 어떨지 제안해본다.

이렇게 클래스를 따로 분리하면 `signIn` 메소드 호출 과정은 다음과 같을 것이다.
```
- 액세스 토큰을 TokenResolver 클래스를 통해 authId로 변환
- authId를 signIn 메소드에 전달
```

### 기대 효과
액세스 토큰을 `authId`로 변환하는 과정을 별도의 클래스로 분리함으로써, `signIn` 메소드를 테스트할 때 액세스 토큰을 생성하지 않고도 `authId` 값으로만 진행할 수 있을 것이다.

2025-01-05 08:26 UTC, jsoonworld commented on ch01~ch02/service/AuthServiceImpl.java
> +public class AuthServiceImpl implements AuthService {
# AuthServiceImpl 개선 제안 및 리팩토링 방안

## 문제점 분석

### 1. 단일 책임 원칙(SRP) 위반
- `AuthServiceImpl` 클래스는 인증, 사용자 관리, 토큰 생성, 웹훅 알림 등 다양한 책임을 가지고 있습니다.
- 이러한 설계는 클래스가 너무 많은 역할을 담당하여 변경에 취약하게 만듭니다.

### 2. 응집도 부족
- 서로 다른 책임이 한 클래스에 응집되어 있습니다.
  - 토큰 생성 (`getFullToken`, `getAccessToken`)
  - 사용자 검색 (`findUserByAuthIdAndType`)
  - 필터 연결 (`connectFilterToUser`)
- 이는 클래스의 응집도를 떨어뜨리고 관리하기 어렵게 만듭니다.

### 3. 과도한 의존성
- 클래스가 여러 서비스와 리포지토리에 의존하고 있습니다.
  - `JwtTokenProvider`, `WebhookService`, `UserRepository` 등과의 강한 결합도가 높습니다.

### 4. 상속 구조가 아닌 인터페이스 사용 부족
- `getAuthId`는 `authType`에 따라 Apple이나 Kakao와 연관된 서비스를 호출하지만, `AuthType`에 의존적입니다.
- 새로운 인증 타입 추가 시 코드 변경이 불가피합니다.

### 5. 객체 간 책임 분배가 불균형
- `AuthServiceImpl`이 거의 모든 로직을 처리하며, 다른 도메인 객체들은 수동적으로 사용되고 있습니다.
- 도메인 객체가 자신의 로직을 더 많이 담당하도록 설계해야 합니다.

### 6. 테스트 어려움
- 여러 기능이 한 클래스에 몰려 있어 단위 테스트가 어렵습니다.
- 각 기능을 독립적으로 테스트할 수 있는 구조가 필요합니다.

### 7. 중복 로직
- `createAccessToken`과 `createRefreshToken`이 거의 동일한 방식으로 동작하지만 별도로 정의되어 있습니다.
- 이는 중복 코드를 초래합니다.

---

## 개선 방안

### 1. 서비스 분리
- 인증 관련 로직 (`signIn`, `signOut`, `signUp`)을 `AuthService`로 분리.
- 필터 관련 로직 (`createAndSaveFilter`, `connectFilterToUser`)을 별도의 `FilterService`로 분리.
- 토큰 생성 로직을 `TokenService`로 분리하여 관련 책임을 위임.

### 2. 전략 패턴 도입
- `getAuthId` 로직에서 `AuthType`별로 다른 서비스를 호출하는 대신, 전략 패턴을 도입하여 인증 타입별 서비스를 동적으로 주입받도록 설계.

```java
public interface AuthProvider {
    String getAuthId(String authAccessToken);
}
```
### 3. DTO 변환 로직 분리
- DTO를 엔티티로 변환하는 로직을 별도의 `Mapper` 클래스로 분리.

```java
public class UserMapper {
    public static User toEntity(SignUpRequestDto requestDto) {
        return User.builder()
                   .authId(requestDto.authId())
                   .name(requestDto.name())
                   .authType(requestDto.authType())
                   .build();
    }
}
```

### 4. 중복 제거
- `createAccessToken`과 `createRefreshToken`의 중복을 제거하여 `createToken` 메서드로 통합.

```java
private String createToken(Authentication authentication, Duration expiration) {
    return jwtTokenProvider.generateToken(authentication, expiration);
}
```

### 5. CustomException 개선
- 예외를 구체적인 하위 클래스로 분리하여 의미를 명확히 하고, 예외 메시지를 `ErrorCode` 또는 `ErrorMessage`와 같은 enum으로 관리.

### 6. 테스트 가능성 향상
- 의존성을 인터페이스로 추상화하고, 주입받는 서비스들을 목(Mock)으로 대체할 수 있도록 설계.

---

## 리팩토링 후 코드 구조

### AuthService
- 사용자 인증, 로그인/로그아웃 처리.

### FilterService
- 필터 생성 및 사용자와의 연결.

### TokenService
- 토큰 생성 및 갱신 처리.

### UserMapper
- DTO와 도메인 객체 간 변환.

## 기대효과

AuthServiceImpl의 책임을 분리하고, 코드의 응집도를 높이며, 유지보수성과 테스트 가능성을 향상시킬 수 있을 것이다.

2025-01-05 08:26 UTC, jsoonworld commented on ch01~ch02/service/AppleServiceImpl.java
> +public class AppleServiceImpl implements AppleService{
# AppleServiceImpl 개선 방안 및 리팩토링

## 문제점 분석 및 개선 방안

### 1. 단일 책임 원칙 (SRP) 위반
- **문제점**:
  - `AppleServiceImpl` 클래스가 HTTP 요청, JSON 파싱, 공개키 생성, JWT 검증 등 다양한 책임을 수행.
  - 단일 책임 원칙 위반으로 클래스 변경에 취약.
- **개선 방안**:
  - 클래스의 역할을 분리:
    - `HttpClient`: HTTP 요청/응답 처리 담당.
    - `PublicKeyParser`: 공개키 생성 및 검증 로직 담당.
    - `JwtTokenParser`: JWT 토큰 파싱 로직 담당.
    - `AppleService`: 비즈니스 로직 중심으로 축소.

### 2. 의존성 강결합
- **문제점**:
  - `ValueConfig`를 직접 참조하여 설정값과의 결합도가 높음.
  - 설정 변경 시 테스트 및 유지보수가 어렵고 재사용성이 낮음.
- **개선 방안**:
  - 설정값을 인터페이스로 주입하여 느슨한 결합 유지:
    ```java
    public interface AppleConfig {
        String getAppleUri();
        String getBearerHeader();
        String getTokenValueDelimiter();
    }
    ```

### 3. 테스트 가능성 부족
- **문제점**:
  - `HttpURLConnection` 등 직접적인 객체 의존으로 테스트 시 목(mock) 처리 어려움.
  - 긴 메서드와 응집된 로직으로 단위 테스트 작성이 어려움.
- **개선 방안**:
  - HTTP 요청/응답 처리 추상화:
    ```java
    public interface HttpClient {
        String get(String uri);
    }
    ```

### 4. 예외 처리 방식 개선
- **문제점**:
  - `RuntimeException` 남용으로 에러 맥락 파악이 어려움.
  - 예외 메시지가 하드코딩되어 가독성과 재사용성이 낮음.
- **개선 방안**:
  - 상황별 구체적인 예외 클래스 정의:
    ```java
    public class PublicKeyNotFoundException extends CustomException {
        public PublicKeyNotFoundException() {
            super("Matching public key not found.");
        }
    }

    public class InvalidJwtTokenException extends CustomException {
        public InvalidJwtTokenException() {
            super("Invalid JWT token.");
        }
    }
    ```

### 5. 코드 중복 문제
- **문제점**:
  - `sendHttpRequest`, `getHttpResponse`, `splitResponse` 등 중복 코드 다수 존재.
  - 공개키 생성 로직(`makePublicKey`)에서도 중복 처리.
- **개선 방안**:
  - 공통 유틸리티 클래스 도입:
    ```java
    public class HttpResponseUtil {
        public static String getResponse(HttpURLConnection connection) throws IOException {
            try (BufferedReader reader = new BufferedReader(new InputStreamReader(connection.getInputStream()))) {
                return reader.lines().collect(Collectors.joining());
            }
        }
    }
    ```

### 6. 메서드 단일 책임 부족
- **문제점**:
  - 하나의 메서드가 여러 작업을 처리하여 가독성이 떨어짐.
  - 예: `makePublicKey`는 토큰 해독, 키 검증, 공개키 생성 등 혼합 처리.
- **개선 방안**:
  - 메서드 분리:
    ```java
    private String extractTokenHeader(String token) {
        val decodeArray = token.split(ValueConfig.TOKEN_VALUE_DELIMITER);
        return new String(Base64.getDecoder().decode(getTokenFromBearerString(decodeArray[0])));
    }

    private JsonObject parseTokenHeader(String header) {
        return (JsonObject) JsonParser.parseString(header);
    }
    ```

### 7. 데이터 파싱 책임 분리
- **문제점**:
  - JSON 데이터 파싱 로직이 서비스 클래스에 혼재.
- **개선 방안**:
  - JSON 파싱 유틸리티 분리:
    ```java
    public class JsonParserUtil {
        public static JsonArray parseJsonArray(String jsonString, String key) {
            JsonObject jsonObject = JsonParser.parseString(jsonString).getAsJsonObject();
            return jsonObject.get(key).getAsJsonArray();
        }
    }
    ```

---

## 리팩토링된 코드 구조

### 1. `AppleServiceImpl` 리팩토링
```java
@Service
@RequiredArgsConstructor
@Transactional(readOnly = true)
public class AppleServiceImpl implements AppleService {

    private final HttpClient httpClient;
    private final PublicKeyParser publicKeyParser;
    private final JwtTokenParser jwtTokenParser;

    @Override
    public String getAppleData(String authAccessToken) {
        String publicKeyResponse = httpClient.get(valueConfig.getAppleUri());
        JsonArray publicKeys = JsonParserUtil.parseJsonArray(publicKeyResponse, "keys");
        PublicKey publicKey = publicKeyParser.create(authAccessToken, publicKeys);

        return jwtTokenParser.parseUserId(authAccessToken, publicKey);
    }
}
```

### 2. `PublicKeyParser` 클래스
```java
public class PublicKeyParser {

    public PublicKey create(String token, JsonArray publicKeyList) {
        String header = extractTokenHeader(token);
        JsonObject tokenHeader = parseTokenHeader(header);

        JsonObject matchingKey = findMatchingKey(publicKeyList, tokenHeader);
        return generatePublicKey(matchingKey);
    }

    private String extractTokenHeader(String token) {
        // 토큰 헤더 추출
    }

    private JsonObject findMatchingKey(JsonArray keys, JsonObject tokenHeader) {
        // 일치하는 공개키 검색
    }

    private PublicKey generatePublicKey(JsonObject key) {
        // 공개키 생성
    }
}
```

### 3. `HttpClient` 클래스
```java
public class HttpClientImpl implements HttpClient {

    @Override
    public String get(String uri) {
        try {
            HttpURLConnection connection = (HttpURLConnection) new URL(uri).openConnection();
            connection.setRequestMethod("GET");
            return HttpResponseUtil.getResponse(connection);
        } catch (IOException e) {
            throw new RuntimeException("Failed to fetch data from: " + uri, e);
        }
    }
}
```

---

## 기대 효과

### 1. **책임 분리로 가독성 및 유지보수성 향상**
- 클래스 및 메서드의 역할이 명확해져 코드 가독성이 크게 향상된다.
- 변경 요구사항이 발생했을 때 해당 책임만 수정하면 되므로 유지보수가 쉬워진다.

### 2. **중복 코드 제거**
- 공통 유틸리티 클래스를 도입하여 코드 중복이 제거되며, 코드 품질이 개선된다.

### 3. **테스트 가능성 증대**
- HTTP 요청과 JWT 파싱 로직을 추상화하여 단위 테스트 및 목(mock) 테스트 작성이 용이해진다.
- 주요 기능을 독립적으로 검증할 수 있어 테스트 효율성이 높아진다.

### 4. **확장성 확보**
- 새로운 기능 추가 시 기존 코드를 수정할 필요 없이, 인터페이스 및 유틸리티 클래스를 확장하여 적용할 수 있다.

### 5. **예외 처리 개선**
- 구체적인 예외 클래스를 사용하여 에러의 원인을 명확히 파악할 수 있으며, 디버깅 시간이 단축.

### 6. **유지보수 비용 절감**
- 코드 구조가 간결하고 모듈화되어 유지보수에 필요한 리소스와 시간이 절감됨

2025-01-05 08:26 UTC, jsoonworld commented on ch01~ch02/service/KakaoServiceImpl.java
> +public class KakaoServiceImpl implements KakaoService {
### KakaoServiceImpl 리팩토링 제안

##### 1. 단일 책임 원칙(SRP) 위반
- `KakaoServiceImpl` 클래스는 HTTP 요청 처리, 응답 변환, 예외 처리 등 여러 책임을 가지고 있다.
- 각 책임을 분리하여 클래스의 응집도를 높이고 유지보수를 용이하게 해야한다.

**개선 방안:**
- HTTP 요청/응답 처리를 별도의 `KakaoApiClient` 클래스로 분리.
- JSON 데이터를 DTO로 매핑하여 구조화된 데이터 처리.

##### 2. 강한 의존성
- `RestTemplate`과 `ObjectMapper`에 강하게 결합되어 있습니다. 이는 테스트 및 확장성을 저하시킨다.

**개선 방안:**
- HTTP 클라이언트를 추상화하여 인터페이스를 통해 의존성을 주입받도록 설계.
- 외부 설정(`ValueConfig`)을 활용해 유연성을 확보.

##### 3. Magic String 사용
- `"Authorization"`, `"id"`와 같은 하드코딩된 문자열이 존재하여 코드의 의도를 명확히 파악하기 어렵다.

**개선 방안:**
- 문자열 상수를 별도의 `Constants` 클래스로 정의하여 재사용 가능성과 가독성 향상.

##### 4. 예외 처리 개선
- `CustomException`은 실패 원인을 포함하지 않아 디버깅이 어렵다.

**개선 방안:**
- 예외 메시지에 HTTP 상태 코드와 상세 오류 정보를 포함.

##### 5. 테스트 어려움
- `RestTemplate`와 같은 외부 의존성이 직접 사용되어 단위 테스트에서 Mocking이 어렵다.

**개선 방안:**
- `RestTemplate` 호출 로직을 별도의 클라이언트 클래스로 추상화.
- 인터페이스를 통해 서비스 계층의 테스트 가능성을 높임.

---

#### **리팩토링 코드**

##### **KakaoApiClient** (HTTP 요청/응답 처리 분리)
```java
@RequiredArgsConstructor
public class KakaoApiClient {
    private final RestTemplate restTemplate;
    private final ObjectMapper objectMapper;
    private final ValueConfig valueConfig;

    public KakaoUserResponse fetchUserData(String authAccessToken) {
        try {
            HttpHeaders headers = new HttpHeaders();
            headers.add("Authorization", authAccessToken);

            HttpEntity<Void> requestEntity = new HttpEntity<>(headers);
            Object response = restTemplate.postForEntity(valueConfig.getKakaoUri(), requestEntity, Object.class).getBody();

            return objectMapper.convertValue(response, KakaoUserResponse.class);
        } catch (Exception e) {
            throw new CustomException(FAILED_SOCIAL_LOGIN, e);
        }
    }
}
```

##### **KakaoServiceImpl** (리팩토링된 서비스 클래스)
```java
@RequiredArgsConstructor
@Service
@Transactional(readOnly = true)
public class KakaoServiceImpl implements KakaoService {
    private final KakaoApiClient kakaoApiClient;

    @Override
    public String getKakaoData(String authAccessToken) {
        KakaoUserResponse response = kakaoApiClient.fetchUserData(authAccessToken);
        return response.getId();
    }
}
```

##### **KakaoUserResponse** (DTO 사용)
```java
@Data
public class KakaoUserResponse {
    private String id;
    // 필요한 다른 필드 추가
}
```

##### **ValueConfig** (외부 설정 활용)
```java
@Configuration
@ConfigurationProperties(prefix = "social.kakao")
public class ValueConfig {
    private String uri;
}
```

---

#### **리팩토링의 장점**
1. **SRP 준수**: 각 클래스가 단일 책임을 가지며 변경에 덜 민감해짐.
2. **가독성 향상**: DTO 사용으로 응답 데이터를 명확히 표현.
3. **유연성 확보**: HTTP 클라이언트를 추상화하여 다른 클라이언트로 쉽게 교체 가능.
4. **테스트 용이성**: `KakaoApiClient`를 Mocking하여 서비스 계층의 단위 테스트 가능.
5. **예외 처리 개선**: 디버깅 정보를 포함한 예외 처리가 가능.

---

#### **기대효과**
이 리팩토링을 통해 `KakaoServiceImpl`의 책임을 명확히 하고, 코드의 가독성, 유지보수성, 테스트 가능성을 크게 개선할 수 있다. 추가적으로, 코드 변경에 따른 영향을 최소화하고 더 나은 확장성을 제공할 수 있다.

2025-01-06 07:09 UTC, minSsan commented on ch01~ch02/service/ScrapServiceImpl.java
> +                .toList();
## 일급 컬렉션을 도입하여 코드 가독성 개선하기

### 문제점
- 코드 가독성

### 원인 분석
- `getMonthlyScrapsList` 메소드의 역할은 월별 스크랩 리스트를 분류하고, 이를 리턴하는 것이다.
- **스크랩 내역을 불러**오고, **이를 분류**하여 **dto로 변환하는 과정**을 모두 `getMonthlyScrapsList` 메소드가 수행하고 있다.
- 이에 따라 서비스 메소드 내에서 스트림 사용이 잦아지고 코드 가독성이 낮아진 것을 확인할 수 있다.

### 해결 방법
- `일급 컬렉션`을 사용하여 불변성을 보장하고 코드 가독성을 높일 수 있다.
    - `데드라인으로 그룹핑한 스크랩 내역들`(= 값)을 하나의 도메인 객체로 다루고, 이에 대한 비즈니스 로직을 도메인 객체 내부에 포함시킨다.
- `일급 컬렉션`을 사용함으로써 외부에 영향을 주지 않고 _"데드라인에 따른 스크랩 분류"_ 관련 요구사항 변동에 쉽게 대처할 수 있다.
    - ex) _'데드라인이 며칠 이상 지난 스크랩은 배제한다'_ 는 요구사항 추가 등

#### 일급 컬렉션 정의
```java
public class ScrapsByDeadline {
    private final Map<LocalDate, List<Scrap>> scrapByDeadline;

    public ScrapsByDeadline(List<Scrap> scraps) {
        scrapByDeadline = scraps.stream()
                .collect(Collectors.groupingBy(s -> s.getInternshipAnnouncement().getDeadline()));
    }

    public List<LocalDate> getDeadlines() {
        return List.copyOf(scrapByDeadline.keySet());
    }

    public List<ScrapDetail> getScrapDetails(LocalDate deadline) {
        return scrapByDeadline.get(deadline).stream()
                    .map(s -> MonthlyListResponseDto.ScrapDetail.of(
                            s.getIntershipAnnouncement().getId(),
                            // ...
                    ))    
                    .toList();
    }
}
```

#### 일급 컬렉션 적용 코드
```java
public List<MonthlyListResponseDto> getMonthlyScrapsAsList(Long userId, int year, int month) {

        //모든 월의 시작일은 1, 마지막일은 해당 다음월의 하루 전
        LocalDate start = LocalDate.of(year, month, 1);
        LocalDate end = start.plusMonths(1).minusDays(1);

        List<Scrap> scraps = scrapRepository.findScrapsByUserIdAndDeadlineBetweenOrderByDeadline(userId, start, end);

        ScrapsByDeadline scrapsByDeadline = new ScrapsByDeadline(scraps);
        List<LocalDate> deadlines = scrapsByDeadline.getDeadlines();

        return deadlines.stream()
                .sorted()
                .map(deadline -> MonthlyListResponseDto.of(
                        deadline.toString(),
                        scrapsByDeadline.getScrapDetails(deadline)
                ))
                .toList();
```
> 기존에는 `getKey`와 `getValue`와 같이 모호한 표현이 사용되었으나, 일급 컬렉션을 적용함으로써 각 값의 의미를 더 명확히 이해할 수 있다.

### 기대 효과
_데드라인에 따른 스크랩 상세 내역들을 분류하는 코드_ 를 더 명확히 이해할 수 있다.

2025-01-10 15:23 UTC, minSsan approved these changes

2025-01-13 06:31 UTC, merged